/**
 * CakeCuttingStyles - restrained game UI for the Cake Cutting mini-game.
 */

import type { CSSProperties } from 'react';
import { styles as sharedStyles } from './MiniGameStyles';

const color = {
  bg: 'rgba(22, 19, 16, 0.96)',
  panel: 'rgba(31, 27, 22, 0.94)',
  panelSoft: 'rgba(43, 37, 29, 0.72)',
  border: 'rgba(212, 174, 104, 0.36)',
  borderSoft: 'rgba(212, 174, 104, 0.18)',
  text: '#efe4cd',
  strong: '#fff0c2',
  muted: '#a89b82',
  dim: '#706754',
  accent: '#d2ae6d',
  cake: '#a9655d',
  cakeLight: '#bd7f68',
  success: '#7da86f',
  danger: '#b96d61',
  warning: '#c79d5b',
};

const panelBase: CSSProperties = {
  backgroundColor: color.panel,
  border: `1px solid ${color.borderSoft}`,
  borderRadius: '6px',
  boxSizing: 'border-box',
};

const tagBase: CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  minHeight: '22px',
  padding: '2px 8px',
  borderRadius: '3px',
  fontSize: '11px',
  fontWeight: 800,
  lineHeight: 1,
  whiteSpace: 'nowrap',
};

const rowBase: CSSProperties = {
  display: 'flex',
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  padding: '8px 10px',
  borderRadius: '4px',
  border: `1px solid ${color.borderSoft}`,
  backgroundColor: 'rgba(255, 255, 255, 0.025)',
  boxSizing: 'border-box',
  width: '100%',
};

export const cakeCuttingStyles: Record<string, CSSProperties> = {
  gameArea: {
    ...sharedStyles.gameArea,
    gap: '10px',
    color: color.text,
  },

  headerRow: {
    ...panelBase,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    minHeight: '54px',
    padding: '10px 14px',
    borderColor: color.border,
  },
  roundLabel: {
    fontSize: '18px',
    fontWeight: 900,
    color: color.strong,
  },
  timerDisplay: {
    fontSize: '20px',
    fontWeight: 900,
    color: color.accent,
    fontFamily: 'monospace',
  },
  statusText: {
    fontSize: '15px',
    fontWeight: 900,
    color: color.warning,
  },

  containerLayout: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    gap: '12px',
    alignItems: 'stretch',
    flexWrap: 'wrap',
    boxSizing: 'border-box',
  },
  leftPlayboard: {
    flex: '2 1 340px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    width: '100%',
    boxSizing: 'border-box',
  },
  rightRuleboard: {
    ...panelBase,
    flex: '1 1 240px',
    display: 'flex',
    flexDirection: 'column',
    padding: '12px',
    gap: '10px',
    height: 'fit-content',
    minWidth: '240px',
  },

  playerGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '7px',
    width: '100%',
  },
  playerCard: rowBase,
  playerCardActive: {
    ...rowBase,
    borderColor: 'rgba(210, 174, 109, 0.56)',
    backgroundColor: 'rgba(210, 174, 109, 0.08)',
  },
  playerCardDead: {
    ...rowBase,
    borderColor: 'rgba(185, 109, 97, 0.24)',
    backgroundColor: 'rgba(185, 109, 97, 0.05)',
    opacity: 0.62,
  },
  playerName: {
    fontSize: '13px',
    fontWeight: 800,
    color: color.text,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  playerNameMe: {
    fontSize: '13px',
    fontWeight: 900,
    color: color.accent,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  badgeMe: {
    ...tagBase,
    minHeight: '18px',
    padding: '1px 6px',
    color: color.accent,
    backgroundColor: 'rgba(210, 174, 109, 0.08)',
    border: '1px solid rgba(210, 174, 109, 0.32)',
    marginLeft: '6px',
  },
  statusBadgeActive: {
    ...tagBase,
    color: color.accent,
    backgroundColor: 'rgba(210, 174, 109, 0.1)',
    border: '1px solid rgba(210, 174, 109, 0.34)',
  },
  statusBadgeWaiting: {
    ...tagBase,
    color: color.muted,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    border: `1px solid ${color.borderSoft}`,
  },
  statusBadgeOut: {
    ...tagBase,
    color: color.danger,
    backgroundColor: 'rgba(185, 109, 97, 0.08)',
    border: '1px solid rgba(185, 109, 97, 0.3)',
  },

  cakeBoard: {
    ...panelBase,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '16px',
    width: '100%',
    padding: '20px 18px',
    backgroundColor: color.bg,
    borderColor: color.border,
  },
  cakeTitle: {
    fontSize: '17px',
    fontWeight: 900,
    color: color.strong,
    margin: 0,
  },
  cakeSubTitle: {
    fontSize: '12px',
    fontWeight: 700,
    color: color.muted,
    margin: '0 0 6px 0',
    textAlign: 'center',
    lineHeight: 1.45,
  },

  cakeTrack: {
    position: 'relative',
    width: '100%',
    height: '62px',
    borderRadius: '5px',
    backgroundColor: 'rgba(255, 255, 255, 0.025)',
    border: `1px solid ${color.borderSoft}`,
    boxSizing: 'border-box',
    overflow: 'visible',
    margin: '8px 0',
  },
  cakeActiveZone: {
    position: 'absolute',
    height: '100%',
    top: 0,
    borderRadius: '4px',
    backgroundColor: color.cake,
    border: `1px solid ${color.cakeLight}`,
    boxSizing: 'border-box',
    transition: 'left 300ms ease, width 300ms ease, background-color 160ms ease',
  },
  cakeActiveZoneResolving: {
    position: 'absolute',
    height: '100%',
    top: 0,
    borderRadius: '4px',
    backgroundColor: color.cakeLight,
    border: `1px solid ${color.accent}`,
    boxSizing: 'border-box',
    transition: 'left 300ms ease, width 300ms ease, background-color 160ms ease',
  },
  knifeLine: {
    position: 'absolute',
    height: '78px',
    width: '2px',
    top: '-8px',
    backgroundColor: color.accent,
    borderRadius: '1px',
    zIndex: 10,
  },
  knifeHandle: {
    position: 'absolute',
    top: '-20px',
    left: '50%',
    transform: 'translateX(-50%)',
    fontSize: '10px',
    fontWeight: 900,
    color: color.accent,
    pointerEvents: 'none',
  },
  lastCutMarker: {
    position: 'absolute',
    height: '62px',
    width: '2px',
    top: 0,
    backgroundColor: color.danger,
    zIndex: 5,
  },

  actionArea: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '10px',
    width: '100%',
    marginTop: '4px',
  },
  cutButton: {
    width: '100%',
    maxWidth: '260px',
    minHeight: '48px',
    borderRadius: '5px',
    border: `1px solid ${color.accent}`,
    backgroundColor: 'rgba(210, 174, 109, 0.1)',
    color: color.strong,
    fontSize: '17px',
    fontWeight: 900,
    cursor: 'pointer',
    transition: 'transform 120ms ease, background-color 120ms ease',
  },
  cutButtonActive: {
    width: '100%',
    maxWidth: '260px',
    minHeight: '48px',
    borderRadius: '5px',
    border: `1px solid ${color.accent}`,
    backgroundColor: color.accent,
    color: '#211b12',
    fontSize: '17px',
    fontWeight: 900,
    cursor: 'pointer',
    transition: 'transform 120ms ease, background-color 120ms ease',
    transform: 'translateY(1px)',
  },
  cutButtonDisabled: {
    width: '100%',
    maxWidth: '260px',
    minHeight: '48px',
    borderRadius: '5px',
    border: `1px solid ${color.borderSoft}`,
    backgroundColor: 'rgba(255, 255, 255, 0.025)',
    color: 'rgba(239, 228, 205, 0.38)',
    fontSize: '15px',
    fontWeight: 800,
    cursor: 'not-allowed',
  },

  rulesPanel: {
    ...panelBase,
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    padding: '20px',
    backgroundColor: color.bg,
    borderColor: color.border,
    gap: '16px',
  },
  rulesHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: '10px',
    width: '100%',
  },
  rulesTitleText: {
    fontSize: '21px',
    fontWeight: 900,
    color: color.strong,
    margin: 0,
  },
  rulesContentLayout: {
    display: 'flex',
    flexDirection: 'row',
    gap: '14px',
    flexWrap: 'wrap',
    width: '100%',
    boxSizing: 'border-box',
  },
  rulesExplainCard: {
    ...panelBase,
    flex: '2 1 360px',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    backgroundColor: color.panelSoft,
    padding: '14px',
  },
  rulesSideCard: {
    ...panelBase,
    flex: '1 1 260px',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    backgroundColor: color.panelSoft,
    padding: '14px',
    justifyContent: 'space-between',
  },
  rulesDescText: {
    fontSize: '13px',
    fontWeight: 700,
    color: color.text,
    margin: 0,
    lineHeight: 1.55,
  },
  rulesBulletList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    margin: '4px 0 0 0',
    paddingLeft: '16px',
  },
  rulesBulletItem: {
    fontSize: '13px',
    fontWeight: 700,
    color: color.muted,
    lineHeight: 1.45,
  },
  rulesChecklistTitle: {
    fontSize: '14px',
    fontWeight: 900,
    color: color.strong,
    margin: '0 0 8px 0',
    textAlign: 'left',
  },
  rulesChecklistGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    width: '100%',
  },
  rulesChecklistItem: rowBase,
  rulesChecklistItemMe: {
    ...rowBase,
    borderColor: 'rgba(210, 174, 109, 0.42)',
    backgroundColor: 'rgba(210, 174, 109, 0.06)',
  },
  rulesPlayerName: {
    fontSize: '12px',
    fontWeight: 800,
    color: color.text,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: '120px',
  },
  rulesPlayerNameMe: {
    fontSize: '12px',
    fontWeight: 900,
    color: color.accent,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: '120px',
  },
  rulesConfirmBtn: {
    width: '100%',
    minHeight: '44px',
    borderRadius: '5px',
    border: `1px solid ${color.success}`,
    backgroundColor: 'rgba(125, 168, 111, 0.12)',
    color: '#d9efcd',
    fontSize: '14px',
    fontWeight: 900,
    cursor: 'pointer',
    transition: 'transform 120ms ease, background-color 120ms ease',
  },
  rulesConfirmBtnDisabled: {
    width: '100%',
    minHeight: '44px',
    borderRadius: '5px',
    border: '1px solid rgba(125, 168, 111, 0.22)',
    backgroundColor: 'rgba(125, 168, 111, 0.045)',
    color: 'rgba(217, 239, 205, 0.55)',
    fontSize: '14px',
    fontWeight: 900,
    cursor: 'not-allowed',
  },
  badgeReady: {
    ...tagBase,
    color: color.success,
    backgroundColor: 'rgba(125, 168, 111, 0.08)',
    border: '1px solid rgba(125, 168, 111, 0.3)',
  },
  badgeThinking: {
    ...tagBase,
    color: color.warning,
    backgroundColor: 'rgba(199, 157, 91, 0.08)',
    border: '1px solid rgba(199, 157, 91, 0.28)',
  },

  spectatorMessage: {
    fontSize: '14px',
    fontWeight: 800,
    color: color.muted,
    textAlign: 'center',
  },
};
