/**
 * TrustDilemmaStyles - game-specific styles for the Trust Dilemma (经典博弈) mini-game
 */

import type { CSSProperties } from 'react';
import { styles as sharedStyles } from './MiniGameStyles';

export const trustDilemmaStyles: Record<string, CSSProperties> = {
  gameArea: sharedStyles.gameArea,

  // ===== Header =====
  headerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    padding: '12px 18px',
    borderRadius: '10px',
    background: 'linear-gradient(90deg, rgba(28, 25, 18, 0.9) 0%, rgba(48, 36, 21, 0.9) 100%)',
    border: '2px solid rgba(255, 233, 172, 0.35)',
    boxShadow: '0 4px 12px rgba(0,0,0,0.2)',
    boxSizing: 'border-box',
    marginBottom: '14px',
  },
  roundLabel: {
    fontSize: '20px',
    fontWeight: 900,
    color: '#fff7d6',
    letterSpacing: '0.05em',
  },
  timerDisplay: {
    fontSize: '28px',
    fontWeight: 900,
    color: '#ff6b6b',
    fontFamily: 'monospace',
  },
  resolvingLabel: {
    fontSize: '18px',
    fontWeight: 900,
    color: '#ffe08a',
  },

  // ===== Main Playground Panel =====
  playboard: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    gap: '16px',
    alignItems: 'center',
  },

  // ===== Ready Status Section (Leaderboard list style) =====
  readyBoard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    width: '100%',
  },
  readyCard: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 14px',
    borderRadius: '8px',
    border: '1.5px solid rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    boxSizing: 'border-box',
    width: '100%',
  },
  readyCardMe: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 14px',
    borderRadius: '8px',
    border: '1.5px solid rgba(100, 180, 255, 0.45)',
    backgroundColor: 'rgba(100, 180, 255, 0.07)',
    boxSizing: 'border-box',
    width: '100%',
    boxShadow: '0 2px 10px rgba(100, 180, 255, 0.12)',
  },
  readyCardFirst: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 14px',
    borderRadius: '8px',
    border: '1.5px solid rgba(255, 215, 0, 0.4)',
    backgroundColor: 'rgba(255, 215, 0, 0.04)',
    boxSizing: 'border-box',
    width: '100%',
    boxShadow: '0 2px 10px rgba(255, 215, 0, 0.08)',
  },
  readyCardFirstMe: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 14px',
    borderRadius: '8px',
    border: '2px solid rgba(255, 215, 0, 0.65)',
    backgroundColor: 'rgba(255, 215, 0, 0.09)',
    boxSizing: 'border-box',
    width: '100%',
    boxShadow: '0 4px 15px rgba(255, 215, 0, 0.18), inset 0 0 8px rgba(255, 215, 0, 0.1)',
  },
  playerName: {
    fontSize: '14px',
    fontWeight: 800,
    color: '#e8e0d0',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  playerNameMe: {
    fontSize: '14px',
    fontWeight: 900,
    color: '#64b4ff',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  playerNameFirst: {
    fontSize: '14px',
    fontWeight: 900,
    color: '#ffd700',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  playerRank: {
    fontSize: '11px',
    fontWeight: 900,
    color: '#e8e0d0',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    padding: '3px 10px',
    borderRadius: '12px',
    border: '1px solid rgba(255, 255, 255, 0.15)',
    minWidth: '55px',
    textAlign: 'center',
  },
  playerRankFirst: {
    fontSize: '11px',
    fontWeight: 900,
    color: '#1c1912',
    backgroundColor: '#ffd700',
    padding: '3px 10px',
    borderRadius: '12px',
    border: '1px solid #ffd700',
    minWidth: '55px',
    textAlign: 'center',
    boxShadow: '0 0 6px rgba(255, 215, 0, 0.35)',
  },
  badgeMeIcon: {
    fontSize: '11px',
    fontWeight: 900,
    color: '#64b4ff',
    backgroundColor: 'rgba(100, 180, 255, 0.15)',
    border: '1.5px solid rgba(100, 180, 255, 0.45)',
    padding: '1px 8px',
    borderRadius: '4px',
    marginLeft: '8px',
    display: 'inline-block',
  },
  badgeMeIconFirst: {
    fontSize: '11px',
    fontWeight: 900,
    color: '#ffd700',
    backgroundColor: 'rgba(255, 215, 0, 0.12)',
    border: '1.5px solid rgba(255, 215, 0, 0.55)',
    padding: '1px 8px',
    borderRadius: '4px',
    marginLeft: '8px',
    display: 'inline-block',
    boxShadow: '0 0 4px rgba(255, 215, 0, 0.15)',
  },
  badgeReady: {
    fontSize: '12px',
    fontWeight: 900,
    color: '#2ecc71',
    backgroundColor: 'rgba(46, 204, 113, 0.15)',
    border: '1px solid rgba(46, 204, 113, 0.4)',
    padding: '4px 10px',
    borderRadius: '5px',
  },
  badgeThinking: {
    fontSize: '12px',
    fontWeight: 900,
    color: '#f39c12',
    backgroundColor: 'rgba(243, 156, 18, 0.15)',
    border: '1px solid rgba(243, 156, 18, 0.4)',
    padding: '4px 10px',
    borderRadius: '5px',
  },

  // ===== Choice Area =====
  choiceArea: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '14px',
    width: '100%',
    padding: '20px 16px',
    borderRadius: '12px',
    backgroundColor: 'rgba(20, 23, 28, 0.95)',
    border: '2px solid rgba(255, 236, 170, 0.3)',
    boxShadow: '0 8px 30px rgba(0,0,0,0.3)',
    boxSizing: 'border-box',
  },
  choicePrompt: {
    fontSize: '16px',
    fontWeight: 900,
    color: '#fff7d6',
    margin: 0,
    textAlign: 'center',
    lineHeight: 1.5,
  },
  choiceButtons: {
    display: 'flex',
    gap: '24px',
    justifyContent: 'center',
    width: '100%',
  },
  buttonC: {
    flex: '1',
    maxWidth: '160px',
    height: '92px',
    borderRadius: '12px',
    border: '2.5px solid #2980b9',
    backgroundColor: 'rgba(41, 128, 185, 0.15)',
    color: '#3498db',
    fontSize: '18px',
    fontWeight: 900,
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    boxShadow: '0 4px 12px rgba(41, 128, 185, 0.2)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
  },
  buttonCSelected: {
    flex: '1',
    maxWidth: '160px',
    height: '92px',
    borderRadius: '12px',
    border: '2.5px solid #27ae60',
    backgroundColor: 'rgba(39, 174, 96, 0.35)',
    color: '#2ecc71',
    fontSize: '18px',
    fontWeight: 900,
    cursor: 'pointer',
    boxShadow: '0 4px 20px rgba(39, 174, 96, 0.45), inset 0 0 10px rgba(46, 204, 113, 0.3)',
    transition: 'all 0.15s ease',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    transform: 'scale(1.05)',
  },
  buttonD: {
    flex: '1',
    maxWidth: '160px',
    height: '92px',
    borderRadius: '12px',
    border: '2.5px solid #c0392b',
    backgroundColor: 'rgba(192, 57, 43, 0.15)',
    color: '#e74c3c',
    fontSize: '18px',
    fontWeight: 900,
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    boxShadow: '0 4px 12px rgba(192, 57, 43, 0.2)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
  },
  buttonDSelected: {
    flex: '1',
    maxWidth: '160px',
    height: '92px',
    borderRadius: '12px',
    border: '2.5px solid #d35400',
    backgroundColor: 'rgba(211, 84, 0, 0.35)',
    color: '#e67e22',
    fontSize: '18px',
    fontWeight: 900,
    cursor: 'pointer',
    boxShadow: '0 4px 20px rgba(211, 84, 0, 0.45), inset 0 0 10px rgba(230, 126, 34, 0.3)',
    transition: 'all 0.15s ease',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    transform: 'scale(1.05)',
  },
  buttonSubtitle: {
    fontSize: '11px',
    fontWeight: 700,
    opacity: 0.85,
  },

  // ===== Resolving Reveal Phase =====
  revealContainer: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    padding: '22px 18px',
    borderRadius: '12px',
    backgroundColor: 'rgba(24, 28, 36, 0.97)',
    border: '2.5px solid #ffd28a',
    boxSizing: 'border-box',
    boxShadow: '0 12px 40px rgba(0,0,0,0.5)',
    animation: 'fadeIn 0.3s ease-out',
    alignItems: 'center',
    gap: '16px',
  },
  revealTitle: {
    fontSize: '18px',
    fontWeight: 900,
    color: '#ffd28a',
    margin: 0,
    letterSpacing: '0.05em',
  },
  revealGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    width: '100%',
  },
  revealRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px 14px',
    borderRadius: '8px',
    border: '1.5px solid rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
  },
  revealRowMe: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px 14px',
    borderRadius: '8px',
    border: '1.5px solid rgba(100, 180, 255, 0.35)',
    backgroundColor: 'rgba(100, 180, 255, 0.06)',
  },
  revealName: {
    fontSize: '14px',
    fontWeight: 800,
    color: '#e8e0d0',
    flex: '1.5',
    textAlign: 'left',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  revealChoiceC: {
    fontSize: '13px',
    fontWeight: 900,
    color: '#2ecc71',
    backgroundColor: 'rgba(46, 204, 113, 0.15)',
    border: '1px solid rgba(46, 204, 113, 0.35)',
    padding: '3px 12px',
    borderRadius: '6px',
    flex: '1',
    textAlign: 'center',
    maxWidth: '80px',
  },
  revealChoiceD: {
    fontSize: '13px',
    fontWeight: 900,
    color: '#e74c3c',
    backgroundColor: 'rgba(231, 76, 60, 0.15)',
    border: '1px solid rgba(231, 76, 60, 0.35)',
    padding: '3px 12px',
    borderRadius: '6px',
    flex: '1',
    textAlign: 'center',
    maxWidth: '80px',
  },
  revealScorePositive: {
    fontSize: '14px',
    fontWeight: 900,
    color: '#2ecc71',
    flex: '1',
    textAlign: 'right',
  },
  revealScoreNegative: {
    fontSize: '14px',
    fontWeight: 900,
    color: '#e74c3c',
    flex: '1',
    textAlign: 'right',
  },
  revealScoreNeutral: {
    fontSize: '14px',
    fontWeight: 900,
    color: '#95a5a6',
    flex: '1',
    textAlign: 'right',
  },

  // ===== General UI elements =====
  spectatorMessage: {
    fontSize: '15px',
    color: '#a0aab8',
    textAlign: 'center',
    padding: '20px',
  },

  // ===== Permanent Ruleboard Styles =====
  containerLayout: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    gap: '14px',
    alignItems: 'stretch',
    flexWrap: 'wrap',
    boxSizing: 'border-box',
  },
  leftPlayboard: {
    flex: '2 1 340px',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    width: '100%',
    boxSizing: 'border-box',
  },
  rightRuleboard: {
    flex: '1 1 240px',
    display: 'flex',
    flexDirection: 'column',
    padding: '14px 12px',
    borderRadius: '12px',
    backgroundColor: 'rgba(20, 23, 28, 0.95)',
    border: '2px solid rgba(255, 233, 172, 0.3)',
    boxShadow: '0 8px 30px rgba(0,0,0,0.35)',
    boxSizing: 'border-box',
    gap: '12px',
    height: 'fit-content',
    minWidth: '240px',
  },
  ruleTitle: {
    fontSize: '16px',
    fontWeight: 900,
    color: '#ffd28a',
    margin: '0 0 2px 0',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    letterSpacing: '0.05em',
  },
  ruleSubtitle: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#a0aab8',
    margin: 0,
    lineHeight: 1.4,
    borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
    paddingBottom: '8px',
  },
  ruleList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  ruleItem: {
    display: 'flex',
    flexDirection: 'column',
    padding: '8px 10px',
    borderRadius: '6px',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    border: '1px solid rgba(255, 255, 255, 0.05)',
    gap: '4px',
    boxSizing: 'border-box',
  },
  ruleItemHighlight: {
    display: 'flex',
    flexDirection: 'column',
    padding: '8px 10px',
    borderRadius: '6px',
    backgroundColor: 'rgba(46, 204, 113, 0.05)',
    border: '1px solid rgba(46, 204, 113, 0.2)',
    gap: '4px',
    boxSizing: 'border-box',
  },
  ruleItemText: {
    fontSize: '12px',
    fontWeight: 800,
    color: '#e8e0d0',
    margin: 0,
  },
  ruleScoreRow: {
    display: 'flex',
    gap: '6px',
    flexWrap: 'wrap',
  },
  badgeRuleC: {
    fontSize: '10px',
    fontWeight: 900,
    color: '#2ecc71',
    backgroundColor: 'rgba(46, 204, 113, 0.15)',
    border: '1px solid rgba(46, 204, 113, 0.3)',
    padding: '1px 5px',
    borderRadius: '4px',
  },
  badgeRuleD: {
    fontSize: '10px',
    fontWeight: 900,
    color: '#e74c3c',
    backgroundColor: 'rgba(231, 76, 60, 0.15)',
    border: '1px solid rgba(231, 76, 60, 0.3)',
    padding: '1px 5px',
    borderRadius: '4px',
  },
};
