/**
 * TrustDilemmaStyles - restrained game UI for the Trust Dilemma mini-game.
 */

import type { CSSProperties } from 'react';
import { styles as sharedStyles } from './MiniGameStyles';

const color = {
  bg: 'rgba(23, 21, 18, 0.96)',
  panel: 'rgba(31, 28, 23, 0.94)',
  panelSoft: 'rgba(42, 37, 29, 0.72)',
  border: 'rgba(214, 184, 113, 0.36)',
  borderSoft: 'rgba(214, 184, 113, 0.18)',
  text: '#efe6cf',
  textStrong: '#fff2c7',
  muted: '#a99c82',
  dim: '#746b59',
  accent: '#d7b568',
  blue: '#7aa2bd',
  success: '#7ca96d',
  danger: '#b86b5f',
  warning: '#c29a5a',
};

const panelBase: CSSProperties = {
  backgroundColor: color.panel,
  border: `1px solid ${color.borderSoft}`,
  borderRadius: '6px',
  boxSizing: 'border-box',
};

const rowBase: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  width: '100%',
  minHeight: '38px',
  padding: '8px 10px',
  borderRadius: '4px',
  backgroundColor: 'rgba(255, 255, 255, 0.025)',
  border: `1px solid ${color.borderSoft}`,
  boxSizing: 'border-box',
};

const tagBase: CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  minHeight: '22px',
  padding: '2px 8px',
  borderRadius: '3px',
  fontSize: '11px',
  fontWeight: 800,
  lineHeight: 1,
  whiteSpace: 'nowrap',
};

const choiceButtonBase: CSSProperties = {
  flex: 1,
  maxWidth: '168px',
  height: '78px',
  borderRadius: '6px',
  backgroundColor: 'rgba(255, 255, 255, 0.025)',
  color: color.text,
  fontSize: '18px',
  fontWeight: 900,
  cursor: 'pointer',
  transition: 'transform 120ms ease, background-color 120ms ease, border-color 120ms ease',
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  justifyContent: 'center',
  gap: '6px',
  boxSizing: 'border-box',
};

export const trustDilemmaStyles: Record<string, CSSProperties> = {
  gameArea: {
    ...sharedStyles.gameArea,
    gap: '10px',
    color: color.text,
  },

  headerRow: {
    ...panelBase,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    minHeight: '54px',
    padding: '10px 14px',
    borderColor: color.border,
  },
  roundLabel: {
    fontSize: '18px',
    fontWeight: 900,
    color: color.textStrong,
  },
  timerDisplay: {
    fontSize: '26px',
    fontWeight: 900,
    color: color.accent,
    fontFamily: 'monospace',
  },
  resolvingLabel: {
    fontSize: '15px',
    fontWeight: 900,
    color: color.warning,
  },

  playboard: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    gap: '12px',
    alignItems: 'center',
  },
  containerLayout: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    gap: '12px',
    alignItems: 'stretch',
    flexWrap: 'wrap',
    boxSizing: 'border-box',
  },
  leftPlayboard: {
    flex: '2 1 340px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    width: '100%',
    boxSizing: 'border-box',
  },
  rightRuleboard: {
    ...panelBase,
    flex: '1 1 240px',
    display: 'flex',
    flexDirection: 'column',
    padding: '12px',
    gap: '10px',
    height: 'fit-content',
    minWidth: '240px',
  },

  readyBoard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '7px',
    width: '100%',
  },
  readyCard: rowBase,
  readyCardMe: {
    ...rowBase,
    borderColor: 'rgba(122, 162, 189, 0.46)',
    backgroundColor: 'rgba(122, 162, 189, 0.07)',
  },
  readyCardFirst: {
    ...rowBase,
    borderColor: 'rgba(215, 181, 104, 0.44)',
    backgroundColor: 'rgba(215, 181, 104, 0.055)',
  },
  readyCardFirstMe: {
    ...rowBase,
    borderColor: 'rgba(215, 181, 104, 0.58)',
    backgroundColor: 'rgba(215, 181, 104, 0.08)',
  },
  playerName: {
    fontSize: '14px',
    fontWeight: 800,
    color: color.text,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  playerNameMe: {
    fontSize: '14px',
    fontWeight: 900,
    color: color.blue,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  playerNameFirst: {
    fontSize: '14px',
    fontWeight: 900,
    color: color.accent,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  playerRank: {
    ...tagBase,
    color: color.muted,
    backgroundColor: 'rgba(255, 255, 255, 0.035)',
    border: `1px solid ${color.borderSoft}`,
    minWidth: '58px',
  },
  playerRankFirst: {
    ...tagBase,
    color: '#201b13',
    backgroundColor: color.accent,
    border: `1px solid ${color.accent}`,
    minWidth: '58px',
  },
  badgeMeIcon: {
    ...tagBase,
    color: color.blue,
    border: '1px solid rgba(122, 162, 189, 0.38)',
    backgroundColor: 'rgba(122, 162, 189, 0.08)',
    marginLeft: '6px',
  },
  badgeMeIconFirst: {
    ...tagBase,
    color: color.accent,
    border: '1px solid rgba(215, 181, 104, 0.46)',
    backgroundColor: 'rgba(215, 181, 104, 0.08)',
    marginLeft: '6px',
  },
  badgeReady: {
    ...tagBase,
    color: color.success,
    backgroundColor: 'rgba(124, 169, 109, 0.09)',
    border: '1px solid rgba(124, 169, 109, 0.34)',
  },
  badgeThinking: {
    ...tagBase,
    color: color.warning,
    backgroundColor: 'rgba(194, 154, 90, 0.08)',
    border: '1px solid rgba(194, 154, 90, 0.3)',
  },

  choiceArea: {
    ...panelBase,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '12px',
    width: '100%',
    padding: '16px',
  },
  choicePrompt: {
    fontSize: '15px',
    fontWeight: 800,
    color: color.text,
    margin: 0,
    textAlign: 'center',
    lineHeight: 1.45,
  },
  choiceButtons: {
    display: 'flex',
    gap: '12px',
    justifyContent: 'center',
    width: '100%',
  },
  buttonC: {
    ...choiceButtonBase,
    border: '1px solid rgba(124, 169, 109, 0.46)',
  },
  buttonCSelected: {
    ...choiceButtonBase,
    border: `1px solid ${color.success}`,
    backgroundColor: 'rgba(124, 169, 109, 0.18)',
    color: '#d9efcd',
    transform: 'translateY(1px)',
  },
  buttonD: {
    ...choiceButtonBase,
    border: '1px solid rgba(184, 107, 95, 0.46)',
  },
  buttonDSelected: {
    ...choiceButtonBase,
    border: `1px solid ${color.danger}`,
    backgroundColor: 'rgba(184, 107, 95, 0.18)',
    color: '#f0c8c1',
    transform: 'translateY(1px)',
  },
  buttonSubtitle: {
    fontSize: '11px',
    fontWeight: 700,
    color: color.muted,
  },

  revealContainer: {
    ...panelBase,
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    padding: '16px',
    alignItems: 'center',
    gap: '12px',
  },
  revealTitle: {
    fontSize: '17px',
    fontWeight: 900,
    color: color.accent,
    margin: 0,
  },
  revealGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '7px',
    width: '100%',
  },
  revealRow: rowBase,
  revealRowMe: {
    ...rowBase,
    borderColor: 'rgba(122, 162, 189, 0.42)',
    backgroundColor: 'rgba(122, 162, 189, 0.06)',
  },
  revealName: {
    fontSize: '13px',
    fontWeight: 800,
    color: color.text,
    flex: '1.5',
    textAlign: 'left',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  revealChoiceC: {
    ...tagBase,
    color: color.success,
    border: '1px solid rgba(124, 169, 109, 0.34)',
    backgroundColor: 'rgba(124, 169, 109, 0.08)',
    minWidth: '58px',
  },
  revealChoiceD: {
    ...tagBase,
    color: color.danger,
    border: '1px solid rgba(184, 107, 95, 0.34)',
    backgroundColor: 'rgba(184, 107, 95, 0.08)',
    minWidth: '58px',
  },
  revealScorePositive: {
    fontSize: '14px',
    fontWeight: 900,
    color: color.success,
    flex: 1,
    textAlign: 'right',
  },
  revealScoreNegative: {
    fontSize: '14px',
    fontWeight: 900,
    color: color.danger,
    flex: 1,
    textAlign: 'right',
  },
  revealScoreNeutral: {
    fontSize: '14px',
    fontWeight: 900,
    color: color.dim,
    flex: 1,
    textAlign: 'right',
  },

  spectatorMessage: {
    fontSize: '15px',
    color: color.muted,
    textAlign: 'center',
    padding: '20px',
  },
  connectingText: sharedStyles.waitingText,
  errorText: sharedStyles.errorText,
  waitingText: sharedStyles.waitingText,

  ruleTitle: {
    fontSize: '15px',
    fontWeight: 900,
    color: color.textStrong,
    margin: 0,
  },
  ruleSubtitle: {
    fontSize: '11px',
    fontWeight: 700,
    color: color.muted,
    margin: 0,
    lineHeight: 1.4,
    paddingBottom: '8px',
  },
  ruleList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '7px',
  },
  ruleItem: {
    display: 'flex',
    flexDirection: 'column',
    padding: '8px',
    borderRadius: '4px',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    border: `1px solid ${color.borderSoft}`,
    gap: '5px',
    boxSizing: 'border-box',
  },
  ruleItemHighlight: {
    display: 'flex',
    flexDirection: 'column',
    padding: '8px',
    borderRadius: '4px',
    backgroundColor: 'rgba(124, 169, 109, 0.055)',
    border: '1px solid rgba(124, 169, 109, 0.22)',
    gap: '5px',
    boxSizing: 'border-box',
  },
  ruleItemText: {
    fontSize: '12px',
    fontWeight: 800,
    color: color.text,
    margin: 0,
  },
  ruleScoreRow: {
    display: 'flex',
    gap: '5px',
    flexWrap: 'wrap',
  },
  badgeRuleC: {
    ...tagBase,
    minHeight: '18px',
    padding: '1px 5px',
    fontSize: '10px',
    color: color.success,
    backgroundColor: 'rgba(124, 169, 109, 0.08)',
    border: '1px solid rgba(124, 169, 109, 0.24)',
  },
  badgeRuleD: {
    ...tagBase,
    minHeight: '18px',
    padding: '1px 5px',
    fontSize: '10px',
    color: color.danger,
    backgroundColor: 'rgba(184, 107, 95, 0.08)',
    border: '1px solid rgba(184, 107, 95, 0.24)',
  },

  rulesPanel: {
    ...panelBase,
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    padding: '20px',
    gap: '16px',
    backgroundColor: color.bg,
    borderColor: color.border,
  },
  rulesHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: '10px',
    width: '100%',
  },
  rulesTitleText: {
    fontSize: '21px',
    fontWeight: 900,
    color: color.textStrong,
    margin: 0,
  },
  rulesTimerText: {
    ...tagBase,
    minHeight: '30px',
    fontSize: '16px',
    color: color.warning,
    border: '1px solid rgba(194, 154, 90, 0.3)',
    backgroundColor: 'rgba(194, 154, 90, 0.08)',
  },
  rulesContentLayout: {
    display: 'flex',
    flexDirection: 'row',
    gap: '14px',
    flexWrap: 'wrap',
    width: '100%',
    boxSizing: 'border-box',
  },
  rulesExplainCard: {
    ...panelBase,
    flex: '2 1 360px',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    padding: '14px',
    backgroundColor: color.panelSoft,
  },
  rulesSideCard: {
    ...panelBase,
    flex: '1 1 260px',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    padding: '14px',
    backgroundColor: color.panelSoft,
    justifyContent: 'space-between',
  },
  rulesSectionTitle: {
    fontSize: '14px',
    fontWeight: 900,
    color: color.accent,
    margin: '0 0 2px 0',
  },
  rulesDescText: {
    fontSize: '13px',
    fontWeight: 700,
    color: color.text,
    margin: 0,
    lineHeight: 1.55,
  },
  rulesBulletList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    margin: '4px 0 0 0',
    paddingLeft: '16px',
  },
  rulesBulletItem: {
    fontSize: '13px',
    fontWeight: 700,
    color: color.muted,
    lineHeight: 1.45,
  },
  rulesChecklistTitle: {
    fontSize: '14px',
    fontWeight: 900,
    color: color.textStrong,
    margin: '0 0 8px 0',
    textAlign: 'left',
  },
  rulesChecklistGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    width: '100%',
  },
  rulesChecklistItem: rowBase,
  rulesChecklistItemMe: {
    ...rowBase,
    borderColor: 'rgba(122, 162, 189, 0.42)',
    backgroundColor: 'rgba(122, 162, 189, 0.06)',
  },
  rulesPlayerName: {
    fontSize: '12px',
    fontWeight: 800,
    color: color.text,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: '120px',
  },
  rulesPlayerNameMe: {
    fontSize: '12px',
    fontWeight: 900,
    color: color.blue,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: '120px',
  },
  rulesConfirmBtn: {
    width: '100%',
    minHeight: '44px',
    borderRadius: '5px',
    border: `1px solid ${color.success}`,
    backgroundColor: 'rgba(124, 169, 109, 0.12)',
    color: '#d9efcd',
    fontSize: '14px',
    fontWeight: 900,
    cursor: 'pointer',
    transition: 'transform 120ms ease, background-color 120ms ease',
  },
  rulesConfirmBtnDisabled: {
    width: '100%',
    minHeight: '44px',
    borderRadius: '5px',
    border: '1px solid rgba(124, 169, 109, 0.22)',
    backgroundColor: 'rgba(124, 169, 109, 0.045)',
    color: 'rgba(217, 239, 205, 0.55)',
    fontSize: '14px',
    fontWeight: 900,
    cursor: 'not-allowed',
  },
};
