/**
 * TypingSpeedStyles - restrained game UI for the Typing Speed mini-game.
 */

import type { CSSProperties } from 'react';
import { styles as sharedStyles } from './MiniGameStyles';

const color = {
  bg: 'rgba(18, 22, 18, 0.96)',
  panel: 'rgba(27, 32, 27, 0.94)',
  panelSoft: 'rgba(35, 41, 35, 0.72)',
  border: 'rgba(185, 166, 103, 0.34)',
  borderSoft: 'rgba(185, 166, 103, 0.17)',
  text: '#e5dfcb',
  strong: '#f4e7bd',
  muted: '#9fa78f',
  dim: '#697060',
  accent: '#c79d5b',
  success: '#7da86f',
  danger: '#b96d61',
};

const panelBase: CSSProperties = {
  backgroundColor: color.panel,
  border: `1px solid ${color.borderSoft}`,
  borderRadius: '6px',
  boxSizing: 'border-box',
};

const tagBase: CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  minHeight: '20px',
  padding: '2px 7px',
  borderRadius: '3px',
  fontSize: '11px',
  fontWeight: 800,
  lineHeight: 1,
  whiteSpace: 'nowrap',
};

export const typingSpeedStyles: Record<string, CSSProperties> = {
  gameArea: {
    ...sharedStyles.gameArea,
    gap: '10px',
    color: color.text,
  },

  headerRow: {
    ...panelBase,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    minHeight: '54px',
    padding: '10px 14px',
    borderColor: color.border,
  },
  roundLabel: {
    fontSize: '18px',
    fontWeight: 900,
    color: color.strong,
  },
  timerDisplay: {
    fontSize: '24px',
    fontWeight: 900,
    color: color.accent,
    fontFamily: 'monospace',
  },
  statusText: {
    fontSize: '15px',
    fontWeight: 800,
    color: color.success,
  },

  containerLayout: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    gap: '12px',
    alignItems: 'stretch',
    flexWrap: 'wrap',
    boxSizing: 'border-box',
  },
  leftPlayboard: {
    flex: '2 1 340px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    width: '100%',
    boxSizing: 'border-box',
  },
  rightRuleboard: {
    ...panelBase,
    flex: '1 1 240px',
    display: 'flex',
    flexDirection: 'column',
    padding: '12px',
    gap: '10px',
    height: 'fit-content',
    minWidth: '260px',
  },

  typingCard: {
    ...panelBase,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '16px',
    width: '100%',
    padding: '22px 18px',
    backgroundColor: color.bg,
    borderColor: color.border,
  },
  textTitle: {
    fontSize: '17px',
    fontWeight: 900,
    color: color.strong,
    margin: 0,
  },
  sentenceContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    lineHeight: 1.75,
    letterSpacing: '0',
    padding: '18px',
    borderRadius: '5px',
    backgroundColor: 'rgba(255, 255, 255, 0.025)',
    border: `1px solid ${color.borderSoft}`,
    width: '100%',
    boxSizing: 'border-box',
    minHeight: '98px',
  },
  charBase: {
    fontSize: '24px',
    fontWeight: 800,
    display: 'inline-block',
    transition: 'color 120ms ease, opacity 120ms ease',
    margin: '0 1px',
  },
  charTyped: {
    color: color.dim,
    opacity: 0.72,
  },
  charUntyped: {
    color: color.success,
    fontWeight: 900,
  },
  charPunctuation: {
    color: color.muted,
    opacity: 0.78,
  },

  inputWrapper: {
    width: '100%',
    maxWidth: '470px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '8px',
    marginTop: '4px',
  },
  typingInput: {
    width: '100%',
    minHeight: '46px',
    borderRadius: '5px',
    padding: '0 14px',
    fontSize: '16px',
    fontWeight: 800,
    color: color.text,
    backgroundColor: 'rgba(255, 255, 255, 0.045)',
    border: `1px solid ${color.border}`,
    outline: 'none',
    boxSizing: 'border-box',
    textAlign: 'center',
    transition: 'background-color 120ms ease, border-color 120ms ease',
  },
  typingInputFocus: {
    width: '100%',
    minHeight: '46px',
    borderRadius: '5px',
    padding: '0 14px',
    fontSize: '16px',
    fontWeight: 800,
    color: color.text,
    backgroundColor: 'rgba(255, 255, 255, 0.065)',
    border: `1px solid ${color.success}`,
    outline: 'none',
    boxSizing: 'border-box',
    textAlign: 'center',
    transition: 'background-color 120ms ease, border-color 120ms ease',
  },
  inputHelpText: {
    fontSize: '12px',
    fontWeight: 700,
    color: color.muted,
    margin: 0,
    textAlign: 'center',
  },

  raceHeader: {
    fontSize: '15px',
    fontWeight: 900,
    color: color.strong,
    margin: '0 0 8px 0',
    textAlign: 'left',
    paddingBottom: '6px',
  },
  playerGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    width: '100%',
  },
  playerCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '7px',
    padding: '9px 10px',
    borderRadius: '4px',
    border: `1px solid ${color.borderSoft}`,
    backgroundColor: 'rgba(255, 255, 255, 0.025)',
    boxSizing: 'border-box',
    width: '100%',
  },
  playerCardFinished: {
    display: 'flex',
    flexDirection: 'column',
    gap: '7px',
    padding: '9px 10px',
    borderRadius: '4px',
    border: '1px solid rgba(125, 168, 111, 0.42)',
    backgroundColor: 'rgba(125, 168, 111, 0.08)',
    boxSizing: 'border-box',
    width: '100%',
  },
  playerMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    gap: '8px',
  },
  playerName: {
    fontSize: '13px',
    fontWeight: 800,
    color: color.text,
    maxWidth: '120px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  playerNameMe: {
    fontSize: '13px',
    fontWeight: 900,
    color: color.accent,
    maxWidth: '120px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  badgeMe: {
    ...tagBase,
    minHeight: '18px',
    padding: '1px 6px',
    color: color.accent,
    backgroundColor: 'rgba(199, 157, 91, 0.08)',
    border: '1px solid rgba(199, 157, 91, 0.32)',
    marginLeft: '6px',
  },
  badgeRank: {
    ...tagBase,
    color: color.success,
    backgroundColor: 'rgba(125, 168, 111, 0.08)',
    border: '1px solid rgba(125, 168, 111, 0.3)',
  },
  badgeProgress: {
    fontSize: '11px',
    fontWeight: 800,
    color: color.muted,
  },

  trackWrapper: {
    position: 'relative',
    width: '100%',
    height: '12px',
    borderRadius: '3px',
    backgroundColor: 'rgba(255, 255, 255, 0.035)',
    border: `1px solid ${color.borderSoft}`,
    overflow: 'hidden',
    boxSizing: 'border-box',
  },
  trackFill: {
    height: '100%',
    borderRadius: '2px',
    backgroundColor: color.success,
    transition: 'width 220ms ease',
  },

  rulesPanel: {
    ...panelBase,
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    padding: '20px',
    backgroundColor: color.bg,
    borderColor: color.border,
    gap: '16px',
  },
  rulesHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: '10px',
    width: '100%',
  },
  rulesTitleText: {
    fontSize: '21px',
    fontWeight: 900,
    color: color.strong,
    margin: 0,
  },
  rulesContentLayout: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    width: '100%',
    boxSizing: 'border-box',
  },
  rulesExplainCard: {
    ...panelBase,
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    backgroundColor: color.panelSoft,
    padding: '14px',
  },
  rulesDescText: {
    fontSize: '14px',
    fontWeight: 700,
    color: color.text,
    margin: 0,
    lineHeight: 1.55,
  },
  rulesBulletList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '7px',
    margin: '4px 0 0 0',
    paddingLeft: '18px',
  },
  rulesBulletItem: {
    fontSize: '13px',
    fontWeight: 700,
    color: color.muted,
    lineHeight: 1.5,
  },
  rulesCountdownBtn: {
    width: '100%',
    minHeight: '44px',
    borderRadius: '5px',
    border: `1px solid ${color.border}`,
    backgroundColor: 'rgba(199, 157, 91, 0.08)',
    color: color.strong,
    fontSize: '15px',
    fontWeight: 900,
    cursor: 'not-allowed',
    boxSizing: 'border-box',
  },

  countdownOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15, 18, 15, 0.9)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
    borderRadius: '6px',
  },
  countdownText: {
    fontSize: '108px',
    fontWeight: 900,
    color: color.accent,
    lineHeight: 1,
  },
  countdownLabel: {
    fontSize: '20px',
    fontWeight: 900,
    color: color.strong,
    marginTop: '10px',
  },

  spectatorMessage: {
    fontSize: '14px',
    fontWeight: 800,
    color: color.muted,
    textAlign: 'center',
  },
};
