/**
 * TypingSpeedStyles - game-specific styles for the Typing Speed (打字速度) mini-game
 */

import type { CSSProperties } from 'react';
import { styles as sharedStyles } from './MiniGameStyles';

export const typingSpeedStyles: Record<string, CSSProperties> = {
  gameArea: sharedStyles.gameArea,

  // ===== Header =====
  headerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    padding: '12px 18px',
    borderRadius: '10px',
    background: 'linear-gradient(90deg, rgba(16, 28, 20, 0.95) 0%, rgba(24, 48, 36, 0.95) 100%)',
    border: '2px solid rgba(46, 204, 113, 0.3)',
    boxShadow: '0 4px 12px rgba(0,0,0,0.2)',
    boxSizing: 'border-box',
    marginBottom: '14px',
  },
  roundLabel: {
    fontSize: '20px',
    fontWeight: 900,
    color: '#e6ffe6',
    letterSpacing: '0.05em',
  },
  timerDisplay: {
    fontSize: '28px',
    fontWeight: 900,
    color: '#2ecc71',
    fontFamily: 'monospace',
    textShadow: '0 0 8px rgba(46, 204, 113, 0.4)',
  },
  statusText: {
    fontSize: '16px',
    fontWeight: 800,
    color: '#b3ffd9',
  },

  containerLayout: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    gap: '14px',
    alignItems: 'stretch',
    flexWrap: 'wrap',
    boxSizing: 'border-box',
  },
  leftPlayboard: {
    flex: '2 1 340px',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    width: '100%',
    boxSizing: 'border-box',
  },
  rightRuleboard: {
    flex: '1 1 240px',
    display: 'flex',
    flexDirection: 'column',
    padding: '16px 14px',
    borderRadius: '12px',
    backgroundColor: 'rgba(16, 24, 20, 0.96)',
    border: '2px solid rgba(46, 204, 113, 0.25)',
    boxShadow: '0 8px 30px rgba(0,0,0,0.35)',
    boxSizing: 'border-box',
    gap: '14px',
    height: 'fit-content',
    minWidth: '260px',
  },

  // ===== Typist Arena =====
  typingCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '20px',
    width: '100%',
    padding: '30px 24px',
    borderRadius: '12px',
    backgroundColor: 'rgba(12, 18, 15, 0.97)',
    border: '2px solid rgba(46, 204, 113, 0.25)',
    boxShadow: '0 8px 30px rgba(0,0,0,0.4)',
    boxSizing: 'border-box',
  },
  textTitle: {
    fontSize: '18px',
    fontWeight: 900,
    color: '#ffd166',
    margin: 0,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  sentenceContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    lineHeight: '1.8',
    letterSpacing: '0.05em',
    padding: '20px',
    borderRadius: '8px',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    border: '1.5px solid rgba(255, 255, 255, 0.04)',
    width: '100%',
    boxSizing: 'border-box',
    minHeight: '100px',
  },
  charBase: {
    fontSize: '24px',
    fontWeight: 800,
    display: 'inline-block',
    transition: 'all 0.15s ease',
    margin: '0 1px',
  },
  charTyped: {
    color: '#6c7a86',
    textShadow: 'none',
    opacity: 0.6,
  },
  charUntyped: {
    color: '#2ecc71',
    textShadow: '0 0 8px rgba(46, 204, 113, 0.5)',
    fontWeight: 900,
  },
  charPunctuation: {
    color: '#8da696',
    opacity: 0.8,
  },

  // ===== Input Field =====
  inputWrapper: {
    width: '100%',
    maxWidth: '460px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '10px',
    marginTop: '10px',
  },
  typingInput: {
    width: '100%',
    height: '48px',
    borderRadius: '24px',
    padding: '0 20px',
    fontSize: '16px',
    fontWeight: 800,
    color: '#e6ffe6',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    border: '2px solid rgba(46, 204, 113, 0.4)',
    outline: 'none',
    boxSizing: 'border-box',
    textAlign: 'center',
    transition: 'all 0.2s ease',
    boxShadow: '0 4px 10px rgba(46, 204, 113, 0.1)',
  },
  typingInputFocus: {
    width: '100%',
    height: '48px',
    borderRadius: '24px',
    padding: '0 20px',
    fontSize: '16px',
    fontWeight: 800,
    color: '#ffffff',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    border: '2px solid #2ecc71',
    outline: 'none',
    boxSizing: 'border-box',
    textAlign: 'center',
    transition: 'all 0.2s ease',
    boxShadow: '0 0 15px rgba(46, 204, 113, 0.35)',
  },
  inputHelpText: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#8da696',
    margin: 0,
    textAlign: 'center',
  },

  // ===== Real-Time Progress Board (Race Track) =====
  raceHeader: {
    fontSize: '15px',
    fontWeight: 900,
    color: '#e6ffe6',
    margin: '0 0 10px 0',
    textAlign: 'center',
    letterSpacing: '0.05em',
    borderBottom: '1.5px solid rgba(46, 204, 113, 0.2)',
    paddingBottom: '8px',
  },
  playerGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    width: '100%',
  },
  playerCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    padding: '10px 12px',
    borderRadius: '8px',
    border: '1.5px solid rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    boxSizing: 'border-box',
    width: '100%',
  },
  playerCardFinished: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    padding: '10px 12px',
    borderRadius: '8px',
    border: '2px solid #2ecc71',
    backgroundColor: 'rgba(46, 204, 113, 0.08)',
    boxSizing: 'border-box',
    width: '100%',
    boxShadow: '0 2px 10px rgba(46, 204, 113, 0.15)',
  },
  playerMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  playerName: {
    fontSize: '13px',
    fontWeight: 800,
    color: '#cbdcd0',
    maxWidth: '120px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  playerNameMe: {
    fontSize: '13px',
    fontWeight: 900,
    color: '#b3ffd9',
    maxWidth: '120px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  badgeMe: {
    fontSize: '10px',
    fontWeight: 900,
    color: '#b3ffd9',
    backgroundColor: 'rgba(179, 255, 217, 0.15)',
    border: '1px solid rgba(179, 255, 217, 0.4)',
    padding: '1px 5px',
    borderRadius: '3px',
    marginLeft: '6px',
  },
  badgeRank: {
    fontSize: '11px',
    fontWeight: 900,
    color: '#2ecc71',
    backgroundColor: 'rgba(46, 204, 113, 0.15)',
    border: '1px solid rgba(46, 204, 113, 0.4)',
    padding: '2px 8px',
    borderRadius: '4px',
  },
  badgeProgress: {
    fontSize: '11px',
    fontWeight: 800,
    color: '#8da696',
  },

  // Track Layout
  trackWrapper: {
    position: 'relative',
    width: '100%',
    height: '14px',
    borderRadius: '7px',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    overflow: 'hidden',
    boxSizing: 'border-box',
  },
  trackFill: {
    height: '100%',
    borderRadius: '6px',
    background: 'linear-gradient(90deg, #27ae60 0%, #2ecc71 100%)',
    boxShadow: '0 0 6px rgba(46, 204, 113, 0.4)',
    transition: 'width 0.3s cubic-bezier(0.25, 0.8, 0.25, 1)',
  },

  // ===== Rules presentation (3s countdown rules) =====
  rulesPanel: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    padding: '24px 20px',
    borderRadius: '16px',
    backgroundColor: 'rgba(12, 18, 15, 0.98)',
    border: '2px solid rgba(46, 204, 113, 0.35)',
    boxShadow: '0 12px 40px rgba(0, 0, 0, 0.6), inset 0 0 15px rgba(46, 204, 113, 0.05)',
    boxSizing: 'border-box',
    gap: '20px',
  },
  rulesHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '2px solid rgba(46, 204, 113, 0.25)',
    paddingBottom: '12px',
    width: '100%',
  },
  rulesTitleText: {
    fontSize: '22px',
    fontWeight: 900,
    color: '#b3ffd9',
    margin: 0,
    letterSpacing: '0.05em',
    textShadow: '0 0 8px rgba(179, 255, 217, 0.3)',
  },
  rulesContentLayout: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    width: '100%',
    boxSizing: 'border-box',
  },
  rulesExplainCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    border: '1.5px solid rgba(255, 255, 255, 0.05)',
    borderRadius: '10px',
    padding: '18px',
    boxSizing: 'border-box',
  },
  rulesDescText: {
    fontSize: '14px',
    fontWeight: 700,
    color: '#cbdcd0',
    margin: 0,
    lineHeight: 1.6,
  },
  rulesBulletList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    margin: '6px 0 0 0',
    paddingLeft: '18px',
  },
  rulesBulletItem: {
    fontSize: '13.5px',
    fontWeight: 700,
    color: '#a3bdae',
    lineHeight: 1.5,
  },
  rulesCountdownBtn: {
    width: '100%',
    height: '46px',
    borderRadius: '8px',
    border: '2px solid rgba(46, 204, 113, 0.4)',
    backgroundColor: 'rgba(46, 204, 113, 0.06)',
    color: '#2ecc71',
    fontSize: '16px',
    fontWeight: 900,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    cursor: 'not-allowed',
    boxSizing: 'border-box',
  },

  // ===== 3-2-1 Countdown Overlay =====
  countdownOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(10, 15, 12, 0.85)',
    backdropFilter: 'blur(8px)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
    borderRadius: '12px',
  },
  countdownText: {
    fontSize: '120px',
    fontWeight: 900,
    color: '#2ecc71',
    textShadow: '0 0 30px rgba(46, 204, 113, 0.8)',
    animation: 'countdownPulse 1s ease-in-out infinite',
  },
  countdownLabel: {
    fontSize: '24px',
    fontWeight: 900,
    color: '#e6ffe6',
    letterSpacing: '0.2em',
    marginTop: '10px',
  },

  spectatorMessage: {
    fontSize: '14px',
    fontWeight: 800,
    color: '#a0aab8',
    textAlign: 'center',
  },
};
